# Generated by Django 3.2.25 on 2024-08-05 13:15

from django.db import migrations
from django.utils import timezone
import logging

logger = logging.getLogger(__name__)

def populate_rbac_userrole_and_projectmembers(apps):
    User = apps.get_model('users','User')
    UserRole = apps.get_model('rbac','UserRole')
    Project = apps.get_model('projects', 'Project')
    ProjectMember = apps.get_model('projects', 'ProjectMember')
    
    logger.info("Creating user role objects")
    users = User.objects.all()
    projects = Project.objects.all()

    for user in users:
        UserRole.objects.create(user_id=user.id, role=3)
    
    now = timezone.now()
    logger.info("Finished creating user role objects")
    logger.info("Creating project members")
    for project in projects:
        ProjectMember.objects.bulk_create([
            ProjectMember(
                enabled=True,
                created_at=now,
                updated_at=now,
                project_id=project.id,
                user_id=user.id
            ) for user in users
        ])
    logger.info("Finished creating project members")

def reverse_populate(apps):
    UserRole = apps.get_model('rbac', 'UserRole')
    ProjectMember = apps.get_model('projects', 'ProjectMember')
    
    UserRole.objects.all().delete()
    ProjectMember.objects.all().delete()

def forward(apps, schema_editor):
    populate_rbac_userrole_and_projectmembers(apps)

def backwards(apps, schema_editor):
    reverse_populate(apps)

class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('projects', '0026_auto_20231103_0020'),
        ('users', '0009_auto_20231201_0001')
    ]

    operations = [
        migrations.RunPython(forward, backwards)
    ]
